name: Pyspark Commons Deploy
env:
  MIN_COVERAGE_REQUIRED: 80
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  python-test-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Set up Spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.3.1'
          hadoop-version: '3'
      - name: Show Spark version
        run: spark-submit --version
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show environments
        run: env
      - name: Run unit tests
        run: |
          coverage run -m pytest
          coverage xml
      - name: Show coverage.xml
        run: cat coverage.xml
      
      
